
from simulation import *
f = TFile.Open("/home/mfiascar/Physics/Accelerator/Simulation/FCC/TOY_V1/HaloDist_studyHaloTCT/plots/HaloStudies.root")

#Amplitude plots
h_sec_A = f.Get("h_secondary_A")
h_ter_A = f.Get("h_tertiary_A")
integral = h_sec_A.Integral() + h_ter_A.Integral()
h_sec_A.Scale(1./integral)
h_ter_A.Scale(1./integral)
c = TCanvas("c","c")
c.cd()
c.SetLogy()
h_sec_A.GetXaxis().SetTitle("A_{r} [#sigma]")
h_sec_A.GetYaxis().SetRangeUser(1e-7,1.)
h_sec_A.SetLineColor(kRed)
h_sec_A.SetMarkerColor(kRed)
h_sec_A.Draw()
h_ter_A.Draw("same")
lineTCP = TLine(7.6,1e-7,7.6,1.)
lineTCP.SetLineStyle(2)
lineTCP.Draw()
lineTCSG = TLine(8.8,1e-7,8.8,1.)
lineTCSG.SetLineStyle(2)
lineTCSG.Draw()
lineTCLA = TLine(12.6,1e-7,12.6,1.)
lineTCLA.SetLineStyle(2)
lineTCLA.Draw()
rs.myMarkerLine(0.6,0.85,"Secondary halo",0.02,kRed,0.04,1,0.03)
rs.myMarkerLine(0.6,0.78,"Tertiary halo",0.02,1,0.04,1,0.03)
c.Print("Secondary_Tertiary_Halo_amplitude_at_TCT.png")

#Amplitude dpoverP plots
h_sec_dpop = f.Get("h_secondary_dpop")
h_sec_dpop.Rebin(2)
h_ter_dpop = f.Get("h_tertiary_dpop")
h_ter_dpop.Rebin(2)
integral = h_sec_dpop.Integral() + h_ter_dpop.Integral()
h_sec_dpop.Scale(1./h_sec_dpop.Integral())
h_ter_dpop.Scale(1./h_ter_dpop.Integral())
c = TCanvas("c","c")
c.cd()
c.SetLogy()
h_sec_dpop.GetXaxis().SetTitle("#Deltap/p")
h_sec_dpop.GetXaxis().SetRangeUser(0.,0.02)
h_sec_dpop.SetLineColor(kRed)
h_sec_dpop.SetMarkerColor(kRed)
h_sec_dpop.Draw()
h_ter_dpop.Draw("same")
rs.myMarkerLine(0.6,0.85,"Secondary halo",0.02,kRed,0.04,1,0.03)
rs.myMarkerLine(0.6,0.78,"Tertiary halo",0.02,1,0.04,1,0.03)
c.Print("Secondary_Tertiary_Halo_dpoverp_at_TCT.png")

#Values for phase space cuts at FCC
emittance = 0.413E-10
betax_tct = 0.1187194276E+05
dispx_tct=0.4955323E-01
coll_tct=10.47
betax_ir7 =0.7459028536E+03
dispx_ir7 =0.5691877E-01
coll_ir7=7.57
betax_tcsg =0.7050238190E+03 #TCSG.B4L2.B1
dispx_tcsg =0.4943636E-02
coll_tcsg=8.8
betax_tcla = 0.7951155449E+03  #TCLA.B6R2.B1
dispx_tcla = 0.1785423E-01
coll_tcla = 12.6
xrange = 2.e-1
plus_tct = TF1("fn_TCLA_plus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_tct.SetParameters(coll_tct,dispx_tct,emittance,betax_tct)
minus_tct = TF1("fn_TCLA_minus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
minus_tct.SetParameters(-1.*coll_tct,dispx_tct,emittance,betax_tct)
plus_tct_i = TF1("fn_TCLA_plus_i","[0]+x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_tct_i.SetParameters(coll_tct,dispx_tct,emittance,betax_tct)
minus_tct_i = TF1("fn_TCLA_minus_i","[0]+x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
minus_tct_i.SetParameters(-1.*coll_tct,dispx_tct,emittance,betax_tct)
plus_ir7 = TF1("fn_IR7_plus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_ir7.SetParameters(coll_ir7,dispx_ir7,emittance,betax_ir7)
minus_ir7 = TF1("fn_IR7_minus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
minus_ir7.SetParameters(-1.*coll_ir7,dispx_ir7,emittance,betax_ir7)
plus_ir7_i = TF1("fn_IR7_plus","[0]+x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_ir7_i.SetParameters(coll_ir7,dispx_ir7,emittance,betax_ir7)
minus_ir7_i = TF1("fn_IR7_minus","[0]+x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
minus_ir7_i.SetParameters(-1.*coll_ir7,dispx_ir7,emittance,betax_ir7)
plus_tcsg =  TF1("fn_TCSG_plus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_tcsg.SetParameters(coll_tcsg,dispx_tcsg,emittance,betax_tcsg)
plus_tcsg_i =  TF1("fn_TCSG_minus","[0]+x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_tcsg_i.SetParameters(coll_tcsg,dispx_tcsg,emittance,betax_tcsg)
plus_tcla =  TF1("fn_TCSG_plus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_tcla.SetParameters(coll_tcla,dispx_tcla,emittance,betax_tcla)
plus_tcla_i =  TF1("fn_TCSG_plus","[0]+x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
plus_tcla_i.SetParameters(coll_tcla,dispx_tcla,emittance,betax_tcla)
minus_tcla =  TF1("fn_TCSG_minus","[0]-x*[1]/sqrt([2]*[3])",-1*xrange,xrange)
minus_tcla.SetParameters(-1.*coll_tcla,dispx_tcla,emittance,betax_tcla)

#Secondary halo: A_vs_dpop
h_secondary_A_vs_dpop = f.Get("h_secondary_A_vs_dpop")
hprofY = h_secondary_A_vs_dpop.ProfileY()
h_secondary_A_vs_dpop.Scale(1./h_secondary_A_vs_dpop.Integral())
rs.setPalette()
c = TCanvas("c2d","c2d")
c.cd()
h_secondary_A_vs_dpop.GetXaxis().SetRangeUser(0.,0.02)
h_secondary_A_vs_dpop.Draw("colz")
plus_tct.SetLineColor(kRed)
plus_tct.SetLineStyle(2)
minus_tct.SetLineColor(kRed)
minus_tct.SetLineStyle(2)
plus_tct_i.SetLineColor(kRed)
plus_tct_i.SetLineStyle(2)
minus_tct_i.SetLineColor(kRed)
minus_tct_i.SetLineStyle(2)
plus_tcsg.SetLineColor(kBlue)
plus_tcsg.SetLineStyle(2)
plus_tcsg_i.SetLineColor(kBlue)
plus_tcsg_i.SetLineStyle(2)
plus_tcla.SetLineColor(8)
plus_tcla.SetLineStyle(2)
plus_tcla_i.SetLineColor(8)
plus_tcla_i.SetLineStyle(2)
plus_tct.Draw("same")
#minus_tct.Draw("same")
#plus_tct_i.Draw("same")
#minus_tct_i.Draw("same")
plus_tcla.Draw("same")
#plus_tcla_i.Draw("same")
plus_tcsg.Draw("same")
#plus_tcsg_i.Draw("same")
plus_ir7.SetLineStyle(2)
minus_ir7.SetLineStyle(2)
plus_ir7_i.SetLineStyle(2)
minus_ir7_i.SetLineStyle(2)
plus_ir7.Draw("same")
#minus_ir7.Draw("same")
plus_ir7_i.Draw("same")
#minus_ir7_i.Draw("same")
c.Print("SecondaryHalo_A_vs_dpop_at_TCT.png")


cp = TCanvas("cp","cp")
cp.cd()
hprofY.GetXaxis().SetTitle("A_{r} [#sigma]")
hprofY.GetYaxis().SetTitle("#Deltap/p")
hprofY.Draw()
cp.Print("SecondaryHalo_profile_at_TCT.png")

#Tertiary halo: A_vs_dpop
h_tertiary_A_vs_dpop = f.Get("h_tertiary_A_vs_dpop")
hprof = h_tertiary_A_vs_dpop.ProfileY()
h_tertiary_A_vs_dpop.Scale(1./h_tertiary_A_vs_dpop.Integral())
rs.setPalette()
c = TCanvas("c2d","c2d")
c.cd()
h_tertiary_A_vs_dpop.GetXaxis().SetRangeUser(0.,0.02)
h_tertiary_A_vs_dpop.Draw("colz")
plus_tct.SetLineColor(kRed)
plus_tct.SetLineStyle(2)
minus_tct.SetLineColor(kRed)
minus_tct.SetLineStyle(2)
plus_tct_i.SetLineColor(kRed)
plus_tct_i.SetLineStyle(2)
minus_tct_i.SetLineColor(kRed)
minus_tct_i.SetLineStyle(2)
plus_tct.Draw("same")
#minus_tct.Draw("same")
#plus_tct_i.Draw("same")
#minus_tct_i.Draw("same")
plus_ir7.SetLineStyle(2)
minus_ir7.SetLineStyle(2)
plus_ir7_i.SetLineStyle(2)
minus_ir7_i.SetLineStyle(2)
plus_tcla.Draw("same")
#plus_tcla_i.Draw("same")
plus_tcsg.Draw("same")
#plus_tcsg_i.Draw("same")
plus_ir7.Draw("same")
#minus_ir7.Draw("same")
plus_ir7_i.Draw("same")
#minus_ir7_i.Draw("same")
c.Print("TertiaryHalo_A_vs_dpop_at_TCT.png")


c = TCanvas("c","c")
c.cd()
hprof.GetXaxis().SetTitle("A_{r} [#sigma]")
hprof.GetXaxis().SetTitle("#Deltap/p")
hprof.Draw()
c.Print("TertiaryHalo_profile_at_TCT.png")
